export const locations = {
    'APAC-Australia': {
        'Sydney Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Melbourne Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Newcastle Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Brisbane Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Perth Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
    },
    'APAC-China': {
        'Beijing Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Shanghai Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Guangzhou Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Shenzhen Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
    },
    'EU-United Kingdom': {
        'London Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Manchester Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Edinburgh Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Birmingham Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Liverpool Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
    },
    'NA-United States': {
        'New York Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Los Angeles Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Chicago Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Houston Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
        'Miami Building': {
            'Floor 1': ['Space A', 'Space B'],
            'Floor 2': ['Space A', 'Space B'],
            'Floor 3': ['Space A', 'Space B'],
            'Floor 4': ['Space A', 'Space B'],
            'Floor 5': ['Space A', 'Space B'],
            'Floor 6': ['Space A', 'Space B'],
        },
    },
}
